variables:
  MAVEN_CLI_OPTS: " --batch-mode -s ci-settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - deploy

deploy:
  stage: deploy
  image: windows-latest
  script:
    - mvn $MAVEN_CLI_OPTS deploy

#  after_script:
#    -