variables:
  MAVEN_CLI_OPTS: " --batch-mode -s ci-settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  BROWSER:
    value: "chrome"
    options:
      - "chrome"
      - "firefox"
      - "edge"
      - "safari"
    description: "The deployment target. Set to 'staging' by default."
  BROWSERSTACK:
    value: "false"
    options:
      - "false"
      - "true"
    description: "Enable browserstack"
  USERS:
    value: "User1"
    options:
      - "User1"
      - "User2"
    description: "User to test with"
  TESTING_ENVIRONMENT:
    value: "https://open.spotify.com/"
    options:
      - "https://open.spotify.com/Staging"
      - "https://open.spotify.com/dev"
    description: "Environment to test against"
  TEST_RUNNER_FILE:
    value: "TestNg.xml"
    options:
      - "TestNg.xml"
    description: "The name of the test runner file"   

stages:
  - build
  - test
  - upload

default:
    tags:
      - pnl-assume-role-none
    cache:
      paths:
        - .m2/repository/
        - target
    artifacts:
      paths:
        - "target/surefire-reports"
        - "ExtentReports/"
      reports:
          junit:
            - target/surefire-reports/junitreports/*.xml
      when: always
      expire_in: 6 months

test:
  stage: test
  image: windows-latest
  rules:
    - if: $BROWSER == "chrome"
      when: always
    - if: $BROWSER == "firefox"
      when: always
  script:
    - mvn $MAVEN_CLI_OPTS test -Duser=$USERS -Durl=$TESTING_ENVIRONMENT -Dbrowser="${BROWSER}_headless" -DsuiteXmlFile=$TEST_RUNNER_FILE

test_edge:
  stage: test
  image: windows-latest
  rules:
    - if: $BROWSER == "edge"
      when: always
  script:
    - mvn $MAVEN_CLI_OPTS test -Duser=$USERS -Durl=$TESTING_ENVIRONMENT -Dbrowser="${BROWSER}_headless" -DsuiteXmlFile=$TEST_RUNNER_FILE
